name: build nomad remote ray driver

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build the Go binary
      run: go build -o nomad-remote-ray-driver

    - name: Upload binary as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: nomad-remote-ray-driver-binary
        path: nomad-remote-ray-driver

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nomad-remote-ray-driver-binary

    - name: Create Tag
      id: tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "::set-output name=TAG::$TAG_NAME"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.TAG }}
        files: nomad-remote-ray-driver
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
